# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b39a4de8cb3b4642b002aea4bdbb664f9f2c3d1331720781d21a1af9500f0657c1c7d3f99237a356bd2711a96c083dd81b6fdeb32a9fc256607d1c63d2e53d20

test:
  secret_key_base: 9cee504e2d09b381fee1a81aed412af80d908c9c8c8fceb6a9a5332e180d43d3a62f46c57a73211d4d251250cdc97b901af123cf2963a9b9006cc064fc6a562e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
